#!/bin/sh

uci set network.lan.ipaddr='10.0.0.11/24'
uci set network.lan.gateway='10.0.0.1'
uci -q delete network.lan.dns
uci add_list network.lan.dns='10.0.0.1'
uci set network.lan.delegate='0'
uci commit network

uci set dropbear.main.enable='1'
uci set dropbear.main.PasswordAuth='on'
uci set dropbear.main.RootPasswordAuth='on'
uci set dropbear.main.Port='9022'
uci set dropbear.main.Interface='lan'
uci commit dropbear

# Keep first boot credential-free and force LuCI/console users to set a password.
passwd -d root 2>/dev/null || sed -i 's#^root:[^:]*:#root::#' /etc/shadow

/etc/init.d/network restart
/etc/init.d/dropbear restart

exit 0
